---
title: "mortAAR: Vignette >>Extended discussion<<"
author: "Nils Müller-Scheeßel"
date: "June 2017"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
csl: "`r library(RCurl); ifelse(url.exists('https://www.zotero.org/styles/journal-of-archaeological-science'), 'https://www.zotero.org/styles/journal-of-archaeological-science', '')`"
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

Life tables have only a marginal position in archaeology research, for different reasons. On the one hand, the columns with rows of many-digit numbers carrying strange labels can be daunting, and indeed, the mathematics behind the construction of life tables based on modern census data are not for the faint-of-heart. Compared to life tables based on real census data, archaeological ones are more straightforward, but their interpretation carries its own problems. First and foremost, they pretend a degree of exactness which is not backed by the underlying data. That is another reason why life-tables are looked at with a certain degree of suspiciousness by archaeologists. And finally, despite the fact that the construction of archaeological life tables can be straightforward, it involves a lot of computation and number-crunching compared to other means used in archaeological discourse. To our knowledge until now, a simple to use and easily accessible tool for computing life tables was lacking. That is why we sat down and put together mortAAR for R. We hope it will be of use for archaeologists world-wide.  

From outer appearance, life tables from modern census data and archaeological ones like generated by mortAAR look very similar. For modern census data, though, there are far more sophisticated measures available. We cannot go into more detail here but refer the reader to the abundant literature on demography and life table construction.

However, perhaps even more important than the different methods of computing the columns are the differences in input data. Due to modern infrastructure, modern census data of developed countries can be regarded as fairly complete and comprehensive. This is, of course, not true for archaeological data. Life tables from modern census data are important tools for inferring the prospective development of a given population. This is, of course, not possible for archaeological data sets. We have to assume that we are dealing with a stationary population.

---

# Overview of features
In our view, mortAAR shines in the following areas:

## Ease and flexibility of input
We took great pains to allow the user as many customisations as feasible. First and foremost, the tables can be of very different types of formatting. A single individual approach is supported as well as already pooled data (e. g. from an already existing life table). In the latter case, the user has to specify a numerical variable which defines the count of each age class.  

In most data sets, the date ranges are defined rather loosely, obviously reflecting the conviction that one year more or less does not count taking the crude methods of age estimation into account. However, for the construction of life tables it should be obvious that 20–40 is not the same as 20–39, because in the former case the individual in question will also contribute to the age class of 40–44 (for 5-year-classes). Therefore, the user should check her data carefully what methodology the data-set she is using (if she has not generated it herself) follows. To spare the user the possible inconvenience to transform her data to conform to any given methodology, both possibilities -- labelled „included“ (e. g. 20–39) and „excluded“ (e.g. 20–40) -- are catered for.  

The custom method of constructing the life table follows the approach used in modern data, so it uses 5 year-classes, except the youngest class. Following Ascadi and Nemeskeri [@acsadi_history_1970], at least for Central Europe it has become practice to publish either the full life table or a collapsed form with five year-intervals (@herrmann_prahistorische_1990, 304ff., @kokkotidis_graberfeld-_1991). However, in international demographic discourse the approach chosen by the UN-life model tables ({Anon., 1982, #58196}) is followed where the first 5-year-age group is subdivided into those having died in their first year of life (0) and those having died in the second to fifth year (1–4). Because this differences are highly relevant in many archaeological contexts and the information is also -- contrary to the possibilities in the higher age groups -- anthropologically quite feasible to get, we decided to choose the UN-approach as the default variant. By that, we hope to enhance the comparability of historic or present-day demographic data and that of archaeological origin. However, if the user has good reasons to do so, she is also allowed to define her own age classes. Furthermore, the user is encouraged to define any possible variable as grouping variable. For an individual cemetery, this will mostly include the sex of the deceased, but it might as well be defined as marking different populations.

## Sophisticated means of computation
To get from time spans of individuals or groups of individuals, as they are usually provided by anthropological studies, to discrete age classes, the time span is exploded to single years; the individual values for these years are then pooled together to whichever age class the user chose initially. It is tempting to define different kernels for the explosion process (e. g. Gaussian), but in our view this solution would not reflect the anthropological diagnosing process correctly: An individual diagnosed of being of adult age in Central European terminology -- that is, 20 to 39 years old -- has the same chances of being truly, say, 22 or 38, and not, as a Gaussian kernel would imply, a highest probability of being 30 years. That is why we decided to follow an equi-divisional approach, so each year of the reported time interval of an individual or a group of individuals gets the same value, essentially the same probability of being the true age.  

While the general steps for computing an archaeological life table are straightforward and -- leaving idiosyncracies like the choice of the size of the radix and the exact formulas aside -- the same, that is: all formulas circulating in archaeological textbooks reach the same results (except possible rounding errors), one detail tends to be overlooked. This detail concerns the average number of years lived of an individual that died within a specific age class a (here called A(x) following the UN tables, elsewhere specified as „nax“). A(x) is of importance for computing L(x), the overall number of years lived within an age class, ultimately used to calculate life expectancy and the reconstruction of population. In virtually all archaeological text books, A(x) is defined as a/2, essentially splitting the length of the age interval in question in half. As we cannot know the exact date of death, given the current set of age estimation methods, this seems at first sensible. The verdict of N. Keyfitz (@keyfitz_applied_1977, 13) -- „The uniform distribution of deaths […] leads to nax = n/2, but this is not acceptable when the age interval n is as wide as 5 years.“ -- has certainly its validity when dealing with modern census data, but might be disregarded for older individuals, as the empirical value for age classes > 5 years is very close to 2.5, the computed value (empirically, it mostly hovers between 2.45 and 2.65 as older individuals tend to die later than the middle of their class, but this is far more difficult to generalize than for the younger age classes [see below]). Interestingly, this problem is valid even for empiric modern life tables for the first age group (0-1 years) where the age of death is recorded only in years, not in months. It seems that Keyfitz ({&Keyfitz, 1970, #87009}, 31) was the first to assume a value for nax to overcome this problem. From empirical data, he came to the following values for the youngest age classes: a0 = 0.07 + 1.7M0, 4a1 = 1.5. Elsewhere (Keyfitz 1977), he has called this "separation factor". Contraintuitively, this separation factor for the youngest age groups is relatively small in developed countries (e. g. ibid. p. 15), but large in development countries or historical data (and, supposedly, also in prehistoric times). This means that if young children die at all in developed countries, they do this very young. In life tables of development countries, the average of lived years for a=0 and a=1-4 hovers around 0.3 and 1.3, thus, we decided to approximate A(x) for age classes <5 with a/3. As we think that taking the „separation factor“ into account is well backed by empirical data (also implied by [@chamberlain_demography_2006], 30), we made the computation with this factor the default. However, if the user does not agree, she is, of course, able to supply her own factor values or to disregard the factor approach altogether.

## Comprehensiveness of output
mortAAR gives life tables for every group the user specified and also on its own one table for all groups combined. Furthermore, it allows to visualize the resulting data sets via curve plots. The user can simply click through the plots for the different key values and thereby get a clear picture about the specifities of each data set, and also -- if more than one category was specified -- about the differences between the data sets.  

Finally, we added the reconstruction of the age distribution of the given population as an additional column (rel_popx), usually not provided by modern standard life tables. Following @kokkotidis_graberfeld-_1991, 227, this is achieved by dividing Lx by T0.

---

# Archaeological example

---

# References
